"""Generated human views of programme state. Never authoritative."""
from __future__ import annotations

from pathlib import Path

from eiflib import write_utf8

from .engine import completion_account, conservation_gaps, effective_status, frontier, is_leaf
from .retroactive import node_is_retroactive
from .runtime_paths import control_command

BANNER = (
    f'<!-- GENERATED by {control_command()}. Do not edit. '
    'Authoritative history: .eif/program/PROGRAM_LOG.ndjson -->\n\n'
)


def write_views(project: Path, state: dict) -> None:
    project = Path(project)
    eif = project / '.eif'
    eif.mkdir(parents=True, exist_ok=True)
    write_utf8(eif / 'PROGRAM.md', BANNER + program_md(state))
    write_utf8(eif / 'CURRENT.md', BANNER + current_md(state))
    write_utf8(eif / 'ROADMAP.md', BANNER + roadmap_md(state))
    write_utf8(eif / 'ESCALATION.md', BANNER + escalation_md(state))
    leased = [n for n in state['nodes'].values() if n.get('lease')]
    write_utf8(eif / 'WORK_ITEM.md', BANNER + work_item_md(state, leased[0] if leased else None))


def program_md(state: dict) -> str:
    p = state['programme']
    ch = p.get('charter') or {}
    lines = [
        f"# Programme {p.get('id') or ''}",
        '',
        f"**Status:** {p.get('status')}  ",
        f"**Charter:** {ch.get('status')}  ",
        f"**Snapshot revision:** {p.get('snapshot_revision')}",
        '',
        '## Outcome (verbatim)',
        '',
        p.get('outcome_statement') or '_unset_',
        '',
        '## Conservation nouns',
        '',
        ', '.join(p.get('conservation_nouns') or []) or '_none_',
        '',
        '## Gaps',
        '',
        ', '.join(conservation_gaps(state)) or '_none_',
        '',
        '## Nodes',
        '',
        '| ID | Title | Class | Recorded | Effective | Leaf | Retro |',
        '|---|---|---|---|---|---|---|',
    ]
    for nid, n in sorted(state['nodes'].items()):
        retro = 'yes' if node_is_retroactive(n) else ''
        lines.append(
            f"| {nid} | {n.get('title')} | {n.get('class')} | {n.get('status')} | "
            f"{effective_status(state, nid)} | {'yes' if is_leaf(state, nid) else 'no'} | {retro} |"
        )
    return '\n'.join(lines) + '\n'


def current_md(state: dict) -> str:
    fr = frontier(state)
    p = state.get('programme') or {}
    cmd = control_command()
    lines = [
        '# Current frontier',
        '',
        '## Programme control',
        '',
        f"- **Programme:** {p.get('id') or '_unset_'}",
        f"- **Charter:** {((p.get('charter') or {}).get('status')) or '_unset_'}",
        f'- **Interface:** `{cmd}` (EIF-namespaced host runtime; never invoke the EIF framework checkout)',
        f'- **Status:** `{cmd} status`',
        f'- **Integrity:** `{cmd} verify`',
        f'- **Frontier:** `{cmd} frontier`',
        '',
        '## Ready leaves',
        '',
    ]
    if not fr:
        lines.append('_No ready unblocked leaves._')
    for nid in fr:
        n = state['nodes'][nid]
        mark = ' RETROACTIVE' if node_is_retroactive(n) else ''
        lines.append(f"- **{nid}** {n.get('title')} ({n.get('class')}, {n.get('risk')}, stage={n.get('stage')}){mark}")
    leased = [n for n in state['nodes'].values() if n.get('lease')]
    lines += ['', '## In progress / leased', '']
    if not leased:
        lines.append('_none_')
    for n in leased:
        lease = n.get('lease') or {}
        lines.append(
            f"- **{n['id']}** {n.get('title')} stage={n.get('stage')} "
            f"run={lease.get('run')} expires={lease.get('expires_at')} note={n.get('stage_note') or ''}"
        )
    dq = [d for d in state['decisions'].values() if d.get('status') == 'proposed']
    lines += ['', '## Decision queue', '']
    if not dq:
        lines.append('_empty_')
    for d in dq:
        lines.append(f"- **{d['id']}** scope={d.get('scope')}: {d.get('statement')}")
    return '\n'.join(lines) + '\n'


def roadmap_md(state: dict) -> str:
    lines = ['# Roadmap (node tree)', '']
    roots = [i for i, n in state['nodes'].items() if not n.get('parent')]
    for r in sorted(roots):
        _tree(state, r, lines, 0)
    return '\n'.join(lines) + '\n'


def _tree(state, nid, lines, depth):
    n = state['nodes'][nid]
    pad = '  ' * depth
    mark = ' RETROACTIVE' if node_is_retroactive(n) else ''
    lines.append(
        f"{pad}- {nid} **{n.get('title')}** `{n.get('status')}`/`{effective_status(state, nid)}` "
        f"({n.get('class')}){mark}"
    )
    for c in sorted(x for x, nn in state['nodes'].items() if nn.get('parent') == nid):
        _tree(state, c, lines, depth + 1)


def escalation_md(state: dict) -> str:
    lines = ['# Escalation / decision queue', '']
    blockers = []
    for n in state['nodes'].values():
        for b in n.get('blockers') or []:
            blockers.append((n['id'], b))
    decisions = [d for d in state['decisions'].values() if d.get('status') == 'proposed']
    findings = list(state.get('deferred_findings') or [])
    if not blockers and not decisions and not findings:
        lines.append('_No open blockers, proposed decisions, or deferred findings._')
        return '\n'.join(lines) + '\n'
    for nid, b in blockers:
        lines.append(f"- blocker **{b.get('id')}** on {nid} type={b.get('type')} ref={b.get('ref')} {b.get('note') or ''}")
    for d in decisions:
        lines.append(f"- decision **{d['id']}** scope={d.get('scope')}: {d.get('statement')}")
    for f in findings:
        lines.append(
            f"- deferred **{f.get('code')}** seq={f.get('seq')} node={f.get('node') or '-'}: {f.get('note')}"
        )
    return '\n'.join(lines) + '\n'


def work_item_md(state: dict, node: dict | None) -> str:
    if not node:
        return '# Work item\n\n_No node is currently leased._\n'
    lines = [
        f"# Work item {node['id']}",
        '',
        f"**Title:** {node.get('title')}  ",
        f"**Class:** {node.get('class')}  ",
        f"**Status:** {node.get('status')}  ",
        f"**Stage:** {node.get('stage')}  ",
        f"**Revision:** {node.get('revision')}  ",
        f"**Risk:** {node.get('risk')}  ",
        f"**Facets:** {', '.join(node.get('facets') or []) or '_none_'}",
        '',
        '## Acceptance criteria',
        '',
    ]
    crit = node.get('acceptance_criteria') or []
    if crit:
        lines.extend(f'- {c}' for c in crit)
    else:
        lines.append('_none_')
    lines += ['', '## Stage note', '', node.get('stage_note') or '_none_', '']
    return '\n'.join(lines) + '\n'


def health_md(state: dict) -> str:
    acc = completion_account(state)
    stale = []
    for n in state['nodes'].values():
        if n.get('baseline_ref') and n.get('status') not in TERMINAL_LOCAL:
            pass
    lines = [
        '# Programme health',
        '',
        f"Open decisions: {len(acc['open_decisions'])}",
        f"Conservation gaps: {', '.join(acc['conservation_gaps']) or 'none'}",
        f"Frontier size: {len(frontier(state))}",
        '',
    ]
    return '\n'.join(lines)


TERMINAL_LOCAL = {'complete', 'deferred', 'rejected', 'split'}
