export type StewardshipSummary = {
  database: string;
  tenant_id: string;
  jobs_last_7d: number;
  jobs_iso_week: number;
  failed_7d: number;
  failed_all: number;
  completed_7d: number;
  completed_all: number;
  pending_7d: number;
  pending_all: number;
  jobs_unarchived: number;
  templates_enabled: number;
  templates_visible_non_admin: number;
  legacy_queue_open: number;
  candidates_needs_review: number;
  candidates_customerish: number;
  candidates_productish: number;
  candidates_distributorish: number;
  products: number;
  customers: number;
  customers_unverified: number;
  distributors: number;
  distributors_unverified: number;
  stores: number;
  audit_events: number;
  labels: Record<string, string>;
  captions: Record<string, string>;
};
