"""Canonical import template specs (shared by Alembic migration and runtime seed)."""

from __future__ import annotations

from typing import Any

# Used by Alembic migration — keep JSON-serializable only.
IMPORT_TEMPLATE_ROWS: list[dict[str, Any]] = [
    {
        "slug": "product_master",
        "display_name": "Product Master / Catalog",
        "description": "SKU-level product specs (foundational master data). Upserts dim_product when applied.",
        "enabled": True,
        "hidden": False,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "product_master_upsert",
        "destructive_apply_requires_confirm": True,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {
            "sku": {
                "aliases": [
                    "item",
                    "item_code",
                    "product_sku",
                    "item_id",
                    "material",
                    "material_code",
                    "sku_code",
                ],
                "required": True,
            },
            "name": {"aliases": ["product_name", "title", "description"], "required": True},
            "category": {"aliases": ["cat", "product_category"], "required": False},
        },
    },
    {
        "slug": "distributor_master",
        "display_name": "Distributor master",
        "description": "Distributor master import with validation + apply upsert into dim_distributor.",
        "enabled": True,
        "hidden": False,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "distributor_master_upsert",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {
            "distributor_code": {"aliases": ["code", "distributor_id", "account_code"], "required": True},
            "distributor_name": {"aliases": ["name", "account_name", "canonical_name"], "required": True},
        },
    },
    {
        "slug": "distributor_inventory",
        "display_name": "Distributor sales & inventory",
        "description": (
            "Distributor-reported sell-out (reseller/customer movement) and dated distributor stock snapshots. "
            "Maps into canonical contracts before apply. Unit sell-out price columns are ex tax / ex VAT where "
            "supplied and are not the same as total revenue. OTW/POD/shipping-like columns are preserved as raw "
            "evidence only and are not applied to inbound shipments."
        ),
        "enabled": True,
        "hidden": False,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "distributor_sales_inventory",
        "destructive_apply_requires_confirm": True,
        "accepted_file_types": [".csv", ".xlsx", ".xlsm", ".xls"],
        "expected_columns": {
            "distributor_token": {
                "aliases": [
                    "disti",
                    "distributor",
                    "distributor code",
                    "distributor name",
                    "distributor_name",
                    "distributor_code",
                    "disti_code",
                    "disti name",
                    "disti_name",
                ],
                "required": True,
            },
            "product_identifier": {
                "aliases": [
                    "sku",
                    "item",
                    "item_code",
                    "item code",
                    "product",
                    "product_sku",
                    "product_code",
                    "product code",
                    "model_code",
                    "modelname",
                    "model name",
                    "part_number",
                    "part number",
                    "part no",
                    "part no.",
                    "partno",
                    "asus part no",
                    "asus part no.",
                    "asus_part_no",
                    "mfg part no",
                    "mfg part no.",
                    "manufacturer part number",
                    "ean",
                    "ean code",
                    "upc",
                    "upc code",
                ],
                "required": True,
            },
            "transaction_date": {
                "aliases": [
                    "date",
                    "transaction date",
                    "transaction_date",
                    "sale_date",
                    "period_date",
                    "report_date",
                    "reporting date",
                    "week date",
                    "invoice date",
                    "invoice_date",
                ],
                "required": False,
            },
            "invoice_no": {
                "aliases": [
                    "invoice",
                    "invoice no",
                    "invoice_no",
                    "invoice number",
                    "invoice_number",
                    "inv_no",
                    "inv no",
                ],
                "required": False,
            },
            "snapshot_date": {
                "aliases": ["as_of_date", "stock_date", "inventory_date", "soh_date"],
                "required": False,
            },
            "quantity_sold": {
                "aliases": [
                    "quantity",
                    "qty",
                    "units",
                    "units sold",
                    "units_sold",
                    "sellout_qty",
                    "sales_qty",
                ],
                "required": False,
            },
            "stock_on_hand": {
                "aliases": [
                    "soh",
                    "stock on hand",
                    "on hand",
                    "on_hand",
                    "stock",
                    "inventory",
                    "closing stock",
                    "inventory_qty",
                    "qty_on_hand",
                ],
                "required": False,
            },
            "customer_dealer_token": {
                "aliases": [
                    "customer",
                    "customer name",
                    "customer_name",
                    "dealer",
                    "dealer name",
                    "dealer_name",
                    "reseller",
                    "reseller name",
                    "account_name",
                    "sold_to",
                ],
                "required": False,
            },
            "dealer_group_token": {
                "aliases": [
                    "dealer name group",
                    "dealer group",
                    "dealer_group",
                    "customer group",
                    "customer_group",
                    "account_group",
                    "account group",
                    "chain",
                ],
                "required": False,
            },
            "unit_sellout_price_ex_tax_amount": {
                "aliases": [
                    "amount",
                    "unit price",
                    "unit_price",
                    "unit sellout price",
                    "unit sell-out price",
                    "unit_sell_price",
                    "sell_price",
                    "price ex vat",
                    "price ex tax",
                    "price_ex_vat",
                    "unit_net_price",
                ],
                "required": False,
            },
            "reported_revenue_amount": {
                "aliases": [
                    "revenue",
                    "line value",
                    "line_revenue",
                    "total value",
                    "total_revenue",
                    "sales value",
                    "sales_value",
                ],
                "required": False,
            },
            "currency_code": {"aliases": ["currency", "curr", "iso_currency"], "required": False},
            "channel_key_token": {"aliases": ["channel", "channel_key", "rtm", "route"], "required": False},
            "region_or_province_token": {"aliases": ["region", "province", "state", "territory"], "required": False},
            "open_channel_evidence": {
                "aliases": ["open_channel", "is_open_channel", "channel_is_open"],
                "required": False,
            },
            "ignored_shipping_evidence": {
                "aliases": [
                    "otw shipped",
                    "otw unshipped",
                    "otw_shipped",
                    "otw_unshipped",
                    "pod qty",
                    "pod_qty",
                    "pod",
                    "tenderremark",
                    "tender_remark",
                ],
                "required": False,
            },
            # D-022 / BACKLOG-082: per-template header policy (not workflow literals).
            # Reserved key — skipped by default_field_mapping / effective_mapping_template.
            "_policy": {
                "exact_target_by_norm": {
                    "customer_name": "customer_dealer_token",
                    "dealer_name_group": "dealer_group_token",
                    "dealer_group": "dealer_group_token",
                },
                "never_auto_map_exact_lower": [
                    "customer code (dealer code)",
                    "dealer name 1",
                    "dealer code",
                ],
                "never_auto_map_norm_regex": [
                    "^dealer_name_\\d+$",
                ],
                "never_auto_map_if": [
                    {"all_of_substrings_lower": ["customer code", "dealer"]},
                    {"all_of_substrings_lower": ["dealer code"]},
                ],
                "prefer_header_norms_for_target": {
                    "customer_dealer_token": ["customer_name", "dealer_name"],
                    "unit_sellout_price_ex_tax_amount": ["unit_price", "unit_sellout_price", "unit_sell_price"],
                },
                "demote_header_norms_for_target": {
                    "unit_sellout_price_ex_tax_amount": [
                        "total_price",
                        "total_value",
                        "line_value",
                        "line_revenue",
                        "total_revenue",
                    ]
                },
            },
        },
    },
    {
        "slug": "customer_master",
        "display_name": "Customer master",
        "description": "Customer account master import with validation + apply upsert into dim_customer.",
        "enabled": True,
        "hidden": False,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "customer_master_upsert",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {
            "customer_code": {"aliases": ["code", "customer_id", "account_code"], "required": True},
            "customer_name": {"aliases": ["name", "account_name"], "required": True},
            "region_code": {"aliases": ["region", "region_id"], "required": False},
            "channel_code": {"aliases": ["channel", "channel_type"], "required": False},
            "customer_status": {"aliases": ["status"], "required": False},
            "partner_tier": {"aliases": ["tier", "partner_tier"], "required": False},
        },
    },
    {
        "slug": "historical_lineup",
        "display_name": "Historical lineup workbook",
        "description": "Workbook-style historical lineups with governed parsing, diagnostics, and normalized history persistence.",
        "enabled": True,
        "hidden": False,
        "admin_only": True,
        "requires_provider": True,
        "pipeline_handler": "historical_lineup_workbook",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx", ".xlsm"],
        "expected_columns": {
            "customer_token": {"aliases": ["customer", "account_name", "customer_code"], "required": False},
            "distributor_token": {"aliases": ["distributor", "disti", "distributor_code"], "required": False},
            "sku_raw": {"aliases": ["sku", "item", "product_sku"], "required": False},
            "quantity_units": {"aliases": ["qty", "quantity", "units"], "required": False},
            "period_label": {"aliases": ["period", "month", "quarter"], "required": False},
        },
    },
    {
        "slug": "current_lineup",
        "display_name": "Current working lineup",
        "description": "Active/proposed commercial lineup uploaded from Commercial Planner. Import intent: current_working_lineup. Not historical evidence.",
        "enabled": True,
        "hidden": True,  # use Commercial Planner parse-upload, not generic imports UI
        "admin_only": False,
        "requires_provider": False,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx", ".xlsm"],
        "expected_columns": {
            "sku_raw": {"aliases": ["sku", "item", "product_sku"], "required": False},
            "part_number_raw": {"aliases": ["part_number", "mpn", "part no"], "required": False},
            "quantity_units": {"aliases": ["qty", "quantity", "units"], "required": False},
            "msrp_local": {"aliases": ["msrp", "srp", "rrp", "list_price", "retail_price"], "required": False},
            "promo_price_evidence_local": {
                "aliases": ["promo_price", "promo_srp", "promo", "deal_price"],
                "required": False,
            },
        },
    },
    {
        # Unified lineup importer — first-class, own multi-file Import-Centre surface (not the generic
        # single-file wizard). Supersedes the embedded Commercial-Planner upload (made read-only) and the
        # admin historical_lineup workbook for go-forward lineups. Each uploaded file becomes one
        # CommercialLineupCase + one async parse job (template_slug=unified_lineup), running the full
        # pricing chain (backwards SRP->DAP) + period/product-line inference.
        "slug": "unified_lineup",
        "display_name": "Lineup (unified import)",
        "description": (
            "Unified multi-file lineup import. Accepts several .csv/.xlsx/.xlsm files in one session and "
            "dispatches one parse job per file. Maps the full pricing chain (SRP, dealer/disti margin, "
            "rebate, VAT, ROE, import tax, net/disti/dealer price, DAP), applies trade-term defaults, runs "
            "the backwards SRP->DAP calculator, and infers reporting period + product line."
        ),
        "enabled": True,
        "hidden": True,  # dedicated multi-file surface in the Import Centre, not the generic wizard
        "admin_only": False,
        "requires_provider": False,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx", ".xlsm"],
        "expected_columns": {
            "sku_raw": {"aliases": ["sku", "item", "product_sku"], "required": False},
            "part_number_raw": {"aliases": ["part_number", "mpn", "part no"], "required": False},
            "model_raw": {"aliases": ["model", "model_name", "series"], "required": False},
            "customer_token": {"aliases": ["customer", "account", "end customer", "sold to"], "required": False},
            "distributor_token": {"aliases": ["distributor", "disti", "channel_partner"], "required": False},
            "quantity_units": {"aliases": ["qty", "quantity", "units"], "required": False},
            "msrp_local": {"aliases": ["msrp", "srp", "rrp", "new srp", "list_price"], "required": False},
            "old_srp_local": {"aliases": ["old srp", "previous srp", "old rrp"], "required": False},
            "dealer_price_evidence_local": {"aliases": ["dealer price"], "required": False},
            "net_price_evidence_local": {"aliases": ["net price", "net"], "required": False},
            "disti_cost_evidence_local": {"aliases": ["disti cost", "distributor cost"], "required": False},
            "actual_dap_evidence_local": {"aliases": ["actual dap"], "required": False},
            "dap_evidence_local": {"aliases": ["dap", "local dap"], "required": False},
            "dealer_margin_pct_evidence": {"aliases": ["dealer margin", "retail margin"], "required": False},
            "rebate_pct_evidence": {"aliases": ["rebate"], "required": False},
            "distributor_margin_pct_evidence": {"aliases": ["disti margin", "distributor margin"], "required": False},
            "import_tax_pct_evidence": {"aliases": ["import tax", "import duty", "duty"], "required": False},
            "roe_evidence": {"aliases": ["roe", "rate of exchange", "exchange rate", "fx rate"], "required": False},
            "vat_pct_evidence": {"aliases": ["vat", "tax_pct"], "required": False},
            "promo_price_evidence_local": {"aliases": ["promo_price", "promo", "deal_price"], "required": False},
        },
    },
    {
        "slug": "bulk_lineup_backfill",
        "display_name": "Bulk historical lineup backfill",
        "description": (
            "File-grain steward panel for historical lineup archive backfill. Multi-file upload, "
            "layered period inference, per-sheet BU fan-out, supersession preview, and batch apply."
        ),
        "enabled": True,
        "hidden": True,
        "admin_only": False,
        "requires_provider": False,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": True,
        "accepted_file_types": [".csv", ".xlsx", ".xlsm"],
        "expected_columns": {},
    },
    {
        "slug": "customer_channel_mapping",
        "display_name": "Customer/channel mapping",
        "description": "Customer classification mapping import (intentionally deferred; not wired for apply yet).",
        "enabled": True,
        "hidden": False,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {
            "customer_code": {"aliases": ["code", "customer_id", "account_code"], "required": True},
            "channel_code": {"aliases": ["channel", "channel_type"], "required": True},
            "region_code": {"aliases": ["region", "region_id"], "required": False},
        },
    },
    {
        "slug": "customer_inventory_sales",
        "display_name": "Customer inventory & sales",
        "description": "Customer-side inventory and/or POS-style sales extracts (pipeline scaffold).",
        "enabled": True,
        "hidden": True,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {"sku": {"aliases": ["item"], "required": True}},
    },
    {
        # Already seeded into the DB by migration 20260518_0045; this row aligns the declarative
        # source of truth with it (no new migration). Values mirror that migration exactly so a
        # re-seed is idempotent. Driven by its own dedicated surface (see capability contract D1),
        # not the generic wizard, but it is a real, pipeline-ready importer.
        "slug": "customer_sell_through",
        "display_name": "Customer Sell-Through Report",
        "description": (
            "Retailer sell-through reports (weekly/monthly file extracts; daily via API in a future phase). "
            "Supports flat, pivoted, multi-sheet, MTD delta, and wide extract layouts."
        ),
        "enabled": True,
        "hidden": False,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "customer_sell_through",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx", ".xlsm"],
        "expected_columns": {
            "units_sold": {
                "aliases": [
                    "units_sold",
                    "qty_sold",
                    "quantity_sold",
                    "tw_sales",
                    "tw sales",
                    "sales",
                    "units",
                    "qty",
                ],
                "required": True,
            },
            # Canonical parser keys (raw_*). Synonym product_identifier is still accepted
            # via normalize_cst_expected_columns for older template rows / steward memory.
            "raw_product_token": {
                "aliases": [
                    "product_code",
                    "sku",
                    "item_code",
                    "itemno",
                    "article",
                    "barcode",
                    "supplier_code",
                ],
                "required": True,
            },
            "raw_location_token": {
                "aliases": ["site_code", "site_name", "store_code", "store_name", "site"],
                "required": False,
            },
            "raw_period_ref": {
                "aliases": [
                    "week",
                    "transaction_week",
                    "transaction week",
                    "period",
                    "report_week",
                    "week_no",
                ],
                "required": False,
            },
            "unit_sell_price": {
                "aliases": [
                    "sell_price",
                    "unit_price",
                    "price",
                    "selling_price",
                    "retail_price",
                    "selling price inc",
                    "list price inc",
                ],
                "required": False,
            },
            "unit_cost": {
                "aliases": [
                    "cost",
                    "unit_cost",
                    "mac",
                    "moving_avg_cost",
                    "cost_price",
                    "cost price",
                    "weighted average cost price",
                ],
                "required": False,
            },
            "reported_soh": {
                "aliases": [
                    "soh",
                    "stock_on_hand",
                    "in_stock",
                    "qty_available",
                    "current_stock",
                    "on_hand",
                    "total_soh",
                    "total_sellable_soh",
                    "qty sellable",
                ],
                "required": False,
            },
        },
    },
    {
        "slug": "inbound_shipments",
        "display_name": "Shipment / order evidence",
        "description": (
            "OEM shipment and open-order extracts (XXOMRPT0025/0027-style CSV, ACZA Shipped/Unship workbook). "
            "Stages canonical evidence lines with raw row JSON; resolves product from Item/EAN/UPC/sales model "
            "and distributor from Bill To / Ship To where deterministic."
        ),
        "enabled": True,
        "hidden": False,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "shipment_evidence_import",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx", ".xlsm"],
        "expected_columns": {
            "operating_unit": {"aliases": ["Operating Unit", "OU NAME", "ou name"], "required": False},
            "bill_to_raw": {"aliases": ["Bill To", "bill to"], "required": False},
            "ship_to_raw": {"aliases": ["Ship To", "ship to"], "required": False},
            "distributor_token": {
                "aliases": [
                    "disti",
                    "distributor",
                    "distributor code",
                    "distributor name",
                    "distributor_name",
                    "distributor_code",
                    "disti_code",
                    "disti name",
                    "disti_name",
                ],
                "required": False,
            },
            "order_no": {
                "aliases": ["Order No.", "Order No", "ORDER NO", "Order number", "order no.", "order no"],
                "required": False,
            },
            "customer_po": {
                "aliases": [
                    "Customer PO",
                    "Cust PO",
                    "Customer P/O",
                    "Purchase Order",
                    "PO No",
                    "PO No.",
                    "PO Number",
                ],
                "required": False,
            },
            "order_line": {"aliases": ["Order Line", "order line"], "required": False},
            "delivery_no": {
                "aliases": [
                    "Delivery No",
                    "Delivery no.",
                    "DELIVERY NO",
                    "Delivery Number",
                    "delivery no",
                    "delivery number",
                ],
                "required": False,
            },
            "invoice_line": {"aliases": ["Invoice Line"], "required": False},
            "item_code": {"aliases": ["Item"], "required": False},
            "sales_model_name": {"aliases": ["Sales Model Name"], "required": False},
            "customer_item": {"aliases": ["Customer Item"], "required": False},
            "ean_code": {"aliases": ["EAN Code"], "required": False},
            "upc_code": {"aliases": ["UPC Code"], "required": False},
            "mpor_item_no": {"aliases": ["MPOR Item No.", "MPOR Item No"], "required": False},
            "quantity": {"aliases": ["Qty", "Qty "], "required": False},
            "unit_price": {"aliases": ["Unit Price"], "required": False},
            "amount": {"aliases": ["Amount"], "required": False},
            "currency_code": {"aliases": ["Currency"], "required": False},
            "ship_confirm_date": {"aliases": ["Ship Confirm Date"], "required": False},
            "schedule_ship_date": {"aliases": ["Schedule Ship Date"], "required": False},
            "promise_date": {"aliases": ["Promise Date"], "required": False},
            "exwork_date": {"aliases": ["Exwork Date"], "required": False},
            "erd_date": {"aliases": ["ERD (Est Revenue Date)"], "required": False},
            "est_pod_date": {
                "aliases": [
                    "Est POD Date",
                    "Estimated POD Date",
                    "Estimated Proof of Delivery",
                    "Expected Delivery Date",
                ],
                "required": False,
            },
            "pod_date": {
                "aliases": [
                    "POD Date",
                    "Proof of Delivery",
                    "Actual Delivery Date",
                    "Delivery Confirmed Date",
                ],
                "required": False,
            },
            "crad_date": {"aliases": ["CRAD", "crad"], "required": False},
            "customer_dealer_token": {
                "aliases": ["Customer Remarks", "Customer Remark", "CUSTOMER REMARKS", "customer remarks"],
                "required": False,
            },
        },
    },
    {
        "slug": "pricing_support",
        "display_name": "Pricing & support (MDF)",
        "description": "List/net pricing and MDF / support rows (pipeline scaffold; admin).",
        "enabled": True,
        "hidden": True,
        "admin_only": True,
        "requires_provider": True,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {"sku": {"aliases": ["item"], "required": True}},
    },
    {
        "slug": "lineup_plan",
        "display_name": "Line-up plan",
        "description": "Assortment / line-up planning rows (preview scaffold; use dedicated bulk flows for full upsert).",
        "enabled": True,
        "hidden": False,
        "admin_only": True,
        "requires_provider": True,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {"sku": {"aliases": ["item"], "required": True}},
    },
    {
        "slug": "promotion_plan",
        "display_name": "Promotion plan (legacy stub)",
        "description": "Deprecated scaffold — use cpor_claim_evidence for settlement claims (U5).",
        "enabled": False,
        "hidden": True,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {"sku": {"aliases": ["item"], "required": True}},
    },
    {
        "slug": "cpor_claim_evidence",
        "display_name": "CPOR claim evidence",
        "description": "Case-scoped settlement claim rows (product × date × units). Prefer case detail upload.",
        "enabled": True,
        "hidden": False,
        "admin_only": True,
        "requires_provider": False,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {
            "product_token": {
                "aliases": ["sku", "item", "item_code", "model", "sales_model", "sales_model_name"],
                "required": True,
            },
            "sale_date": {"aliases": ["date", "transaction_date", "invoice_date"], "required": True},
            "units": {"aliases": ["qty", "quantity", "result_qty", "units_sold"], "required": True},
            "unit_price": {"aliases": ["price", "unit_sell_price"], "required": False},
            "ean": {"aliases": ["ean_code", "barcode"], "required": False},
        },
    },
    {
        "slug": "cpor_historical_cases",
        "display_name": "CPOR historical cases",
        "description": (
            "Bulk import of past CPOR tracking workbooks (case codes preserved). "
            "Steward mapping profile + entity resolve; async apply after steward."
        ),
        "enabled": True,
        "hidden": True,
        "admin_only": True,
        "requires_provider": False,
        "pipeline_handler": "cpor_historical_cases_import",
        "destructive_apply_requires_confirm": True,
        "accepted_file_types": [".xlsx", ".xlsm"],
        "expected_columns": {
            "case_code": {"aliases": ["case id", "case_id"], "required": True},
            "sales_model_token": {
                "aliases": ["sales model name", "sales_model", "model"],
                "required": True,
            },
            "customer_token": {
                "aliases": ["dealer/retailer", "customer", "dealer"],
                "required": True,
            },
        },
    },
]

DEFAULT_SOURCES: list[tuple[str, str, str, str]] = [
    ("product_catalog_default", "Default product catalog feed", "product_master", "catalog"),
    ("distributor_master_default", "Default distributor master feed", "distributor_master", "master_extract"),
    ("customer_master_default", "Default customer master feed", "customer_master", "master_extract"),
    (
        "customer_channel_mapping_default",
        "Default customer/channel mapping feed",
        "customer_channel_mapping",
        "mapping_extract",
    ),
    ("customer_inv_default", "Default customer inventory feed", "customer_inventory_sales", "pos_extract"),
    ("inbound_default", "Default inbound feed", "inbound_shipments", "carrier_extract"),
    ("pricing_support_default", "Default pricing / MDF feed", "pricing_support", "pricing_extract"),
    ("lineup_plan_default", "Default line-up feed", "lineup_plan", "planning_extract"),
    (
        "historical_lineup_default",
        "Default historical lineup feed",
        "historical_lineup",
        "planning_extract",
    ),
    ("promotion_plan_default", "Default promotion plan feed", "promotion_plan", "promo_extract"),
    (
        "cpor_claim_evidence_default",
        "Default CPOR claim evidence feed",
        "cpor_claim_evidence",
        "settlement_extract",
    ),
    (
        "cpor_historical_cases_default",
        "Default CPOR historical tracking workbook feed",
        "cpor_historical_cases",
        "historical_cpor_extract",
    ),
    ("current_lineup_system", "Current working lineup (Commercial Planner upload)", "current_lineup", "planning_extract"),
    ("unified_lineup_system", "Unified lineup import (Import Centre, multi-file)", "unified_lineup", "planning_extract"),
    (
        "bulk_lineup_backfill_system",
        "Bulk historical lineup backfill (Import Centre steward panel)",
        "bulk_lineup_backfill",
        "planning_extract",
    ),
]


def product_master_sample_csv() -> str:
    return (
        "sku,name,category\n"
        "SKU-NEW-99,Example product,Audio\n"
    )
