"""Canonical import template specs (shared by Alembic migration and runtime seed)."""

from __future__ import annotations

from typing import Any

# Used by Alembic migration — keep JSON-serializable only.
IMPORT_TEMPLATE_ROWS: list[dict[str, Any]] = [
    {
        "slug": "product_master",
        "display_name": "Product Master / Catalog",
        "description": "SKU-level product specs (foundational master data). Upserts dim_product when applied.",
        "enabled": True,
        "hidden": False,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "product_master_upsert",
        "destructive_apply_requires_confirm": True,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {
            "sku": {"aliases": ["item", "item_code", "product_sku"], "required": True},
            "name": {"aliases": ["product_name", "title", "description"], "required": True},
            "category": {"aliases": ["cat", "product_category"], "required": False},
            "channel_code": {"aliases": ["channel", "ch_code", "primary_channel"], "required": False},
        },
    },
    {
        "slug": "distributor_master",
        "display_name": "Distributor master",
        "description": "Distributor master import with validation + apply upsert into dim_distributor.",
        "enabled": True,
        "hidden": False,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "distributor_master_upsert",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {
            "distributor_code": {"aliases": ["code", "distributor_id", "account_code"], "required": True},
            "distributor_name": {"aliases": ["name", "account_name", "canonical_name"], "required": True},
        },
    },
    {
        "slug": "distributor_inventory",
        "display_name": "Distributor sales & inventory",
        "description": (
            "Distributor-reported sell-out (reseller/customer movement) and dated distributor stock snapshots. "
            "Maps into canonical contracts before apply. Unit sell-out price columns are ex tax / ex VAT where "
            "supplied and are not the same as total revenue. OTW/POD/shipping-like columns are preserved as raw "
            "evidence only and are not applied to inbound shipments."
        ),
        "enabled": True,
        "hidden": False,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "distributor_sales_inventory",
        "destructive_apply_requires_confirm": True,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {
            "distributor_token": {
                "aliases": [
                    "disti",
                    "distributor",
                    "distributor code",
                    "distributor name",
                    "distributor_name",
                    "distributor_code",
                    "disti_code",
                    "disti name",
                    "disti_name",
                ],
                "required": True,
            },
            "product_identifier": {
                "aliases": [
                    "sku",
                    "item",
                    "item_code",
                    "product",
                    "product_sku",
                    "product_code",
                    "model_code",
                    "modelname",
                    "model name",
                    "part_number",
                    "part number",
                ],
                "required": True,
            },
            "transaction_date": {
                "aliases": [
                    "date",
                    "transaction date",
                    "transaction_date",
                    "sale_date",
                    "period_date",
                    "report_date",
                    "reporting date",
                    "week date",
                ],
                "required": False,
            },
            "invoice_no": {
                "aliases": [
                    "invoice",
                    "invoice no",
                    "invoice_no",
                    "invoice number",
                    "invoice_number",
                    "inv_no",
                    "inv no",
                ],
                "required": False,
            },
            "snapshot_date": {
                "aliases": ["as_of_date", "stock_date", "inventory_date", "soh_date"],
                "required": False,
            },
            "quantity_sold": {
                "aliases": [
                    "quantity",
                    "qty",
                    "units",
                    "units sold",
                    "units_sold",
                    "sellout_qty",
                    "sales_qty",
                ],
                "required": False,
            },
            "stock_on_hand": {
                "aliases": [
                    "soh",
                    "stock on hand",
                    "on hand",
                    "on_hand",
                    "stock",
                    "inventory",
                    "closing stock",
                    "inventory_qty",
                    "qty_on_hand",
                ],
                "required": False,
            },
            "customer_dealer_token": {
                "aliases": [
                    "customer",
                    "customer name",
                    "customer_name",
                    "dealer",
                    "dealer name",
                    "dealer_name",
                    "reseller",
                    "reseller name",
                    "account_name",
                    "sold_to",
                ],
                "required": False,
            },
            "dealer_group_token": {
                "aliases": [
                    "dealer name group",
                    "dealer group",
                    "dealer_group",
                    "customer group",
                    "customer_group",
                    "account_group",
                    "account group",
                    "chain",
                ],
                "required": False,
            },
            "unit_sellout_price_ex_tax_amount": {
                "aliases": [
                    "amount",
                    "unit price",
                    "unit_price",
                    "unit sellout price",
                    "unit sell-out price",
                    "unit_sell_price",
                    "sell_price",
                    "price ex vat",
                    "price ex tax",
                    "price_ex_vat",
                    "unit_net_price",
                ],
                "required": False,
            },
            "reported_revenue_amount": {
                "aliases": [
                    "revenue",
                    "line value",
                    "line_revenue",
                    "total value",
                    "total_revenue",
                    "sales value",
                    "sales_value",
                ],
                "required": False,
            },
            "currency_code": {"aliases": ["currency", "curr", "iso_currency"], "required": False},
            "channel_key_token": {"aliases": ["channel", "channel_key", "rtm", "route"], "required": False},
            "region_or_province_token": {"aliases": ["region", "province", "state", "territory"], "required": False},
            "open_channel_evidence": {
                "aliases": ["open_channel", "is_open_channel", "channel_is_open"],
                "required": False,
            },
            "ignored_shipping_evidence": {
                "aliases": [
                    "otw shipped",
                    "otw unshipped",
                    "otw_shipped",
                    "otw_unshipped",
                    "pod qty",
                    "pod_qty",
                    "pod",
                    "tenderremark",
                    "tender_remark",
                ],
                "required": False,
            },
        },
    },
    {
        "slug": "customer_master",
        "display_name": "Customer master",
        "description": "Customer account master import with validation + apply upsert into dim_customer.",
        "enabled": True,
        "hidden": False,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "customer_master_upsert",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {
            "customer_code": {"aliases": ["code", "customer_id", "account_code"], "required": True},
            "customer_name": {"aliases": ["name", "account_name"], "required": True},
            "region_code": {"aliases": ["region", "region_id"], "required": False},
            "channel_code": {"aliases": ["channel", "channel_type"], "required": False},
            "customer_status": {"aliases": ["status"], "required": False},
            "partner_tier": {"aliases": ["tier", "partner_tier"], "required": False},
        },
    },
    {
        "slug": "historical_lineup",
        "display_name": "Historical lineup workbook",
        "description": "Workbook-style historical lineups with governed parsing, diagnostics, and normalized history persistence.",
        "enabled": True,
        "hidden": False,
        "admin_only": True,
        "requires_provider": True,
        "pipeline_handler": "historical_lineup_workbook",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx", ".xlsm"],
        "expected_columns": {
            "customer_token": {"aliases": ["customer", "account_name", "customer_code"], "required": False},
            "distributor_token": {"aliases": ["distributor", "disti", "distributor_code"], "required": False},
            "sku_raw": {"aliases": ["sku", "item", "product_sku"], "required": False},
            "quantity_units": {"aliases": ["qty", "quantity", "units"], "required": False},
            "period_label": {"aliases": ["period", "month", "quarter"], "required": False},
        },
    },
    {
        "slug": "current_lineup",
        "display_name": "Current working lineup",
        "description": "Active/proposed commercial lineup uploaded from Commercial Planner. Import intent: current_working_lineup. Not historical evidence.",
        "enabled": True,
        "hidden": True,  # use Commercial Planner parse-upload, not generic imports UI
        "admin_only": False,
        "requires_provider": False,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx", ".xlsm"],
        "expected_columns": {
            "sku_raw": {"aliases": ["sku", "item", "product_sku"], "required": False},
            "part_number_raw": {"aliases": ["part_number", "mpn", "part no"], "required": False},
            "quantity_units": {"aliases": ["qty", "quantity", "units"], "required": False},
            "msrp_local": {"aliases": ["msrp", "srp", "rrp", "list_price", "retail_price"], "required": False},
            "promo_price_evidence_local": {
                "aliases": ["promo_price", "promo_srp", "promo", "deal_price"],
                "required": False,
            },
        },
    },
    {
        "slug": "customer_channel_mapping",
        "display_name": "Customer/channel mapping",
        "description": "Customer classification mapping import (intentionally deferred; not wired for apply yet).",
        "enabled": True,
        "hidden": False,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {
            "customer_code": {"aliases": ["code", "customer_id", "account_code"], "required": True},
            "channel_code": {"aliases": ["channel", "channel_type"], "required": True},
            "region_code": {"aliases": ["region", "region_id"], "required": False},
        },
    },
    {
        "slug": "customer_inventory_sales",
        "display_name": "Customer inventory & sales",
        "description": "Customer-side inventory and/or POS-style sales extracts (pipeline scaffold).",
        "enabled": True,
        "hidden": True,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {"sku": {"aliases": ["item"], "required": True}},
    },
    {
        "slug": "inbound_shipments",
        "display_name": "Shipment / order evidence",
        "description": (
            "OEM shipment and open-order extracts (XXOMRPT0025/0027-style CSV, ACZA Shipped/Unship workbook). "
            "Stages canonical evidence lines with raw row JSON; resolves product from Item/EAN/UPC/sales model "
            "and distributor from Bill To / Ship To where deterministic."
        ),
        "enabled": True,
        "hidden": False,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "shipment_evidence_import",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx", ".xlsm"],
        "expected_columns": {
            "operating_unit": {"aliases": ["Operating Unit", "OU NAME", "ou name"], "required": False},
            "bill_to_raw": {"aliases": ["Bill To", "bill to"], "required": False},
            "ship_to_raw": {"aliases": ["Ship To", "ship to"], "required": False},
            "distributor_token": {
                "aliases": [
                    "disti",
                    "distributor",
                    "distributor code",
                    "distributor name",
                    "distributor_name",
                    "distributor_code",
                    "disti_code",
                    "disti name",
                    "disti_name",
                ],
                "required": False,
            },
            "order_no": {
                "aliases": ["Order No.", "Order No", "ORDER NO", "Order number", "order no.", "order no"],
                "required": False,
            },
            "order_line": {"aliases": ["Order Line", "order line"], "required": False},
            "delivery_no": {
                "aliases": [
                    "Delivery No",
                    "Delivery no.",
                    "DELIVERY NO",
                    "Delivery Number",
                    "delivery no",
                    "delivery number",
                ],
                "required": False,
            },
            "invoice_line": {"aliases": ["Invoice Line"], "required": False},
            "item_code": {"aliases": ["Item"], "required": False},
            "sales_model_name": {"aliases": ["Sales Model Name"], "required": False},
            "customer_item": {"aliases": ["Customer Item"], "required": False},
            "ean_code": {"aliases": ["EAN Code"], "required": False},
            "upc_code": {"aliases": ["UPC Code"], "required": False},
            "mpor_item_no": {"aliases": ["MPOR Item No.", "MPOR Item No"], "required": False},
            "quantity": {"aliases": ["Qty", "Qty "], "required": False},
            "unit_price": {"aliases": ["Unit Price"], "required": False},
            "amount": {"aliases": ["Amount"], "required": False},
            "currency_code": {"aliases": ["Currency"], "required": False},
            "ship_confirm_date": {"aliases": ["Ship Confirm Date"], "required": False},
            "schedule_ship_date": {"aliases": ["Schedule Ship Date"], "required": False},
            "promise_date": {"aliases": ["Promise Date"], "required": False},
            "exwork_date": {"aliases": ["Exwork Date"], "required": False},
            "erd_date": {"aliases": ["ERD (Est Revenue Date)"], "required": False},
            "est_pod_date": {
                "aliases": [
                    "Est POD Date",
                    "Estimated POD Date",
                    "Estimated Proof of Delivery",
                    "Expected Delivery Date",
                ],
                "required": False,
            },
            "pod_date": {
                "aliases": [
                    "POD Date",
                    "Proof of Delivery",
                    "Actual Delivery Date",
                    "Delivery Confirmed Date",
                ],
                "required": False,
            },
            "customer_dealer_token": {
                "aliases": ["Customer Remarks", "Customer Remark", "CUSTOMER REMARKS", "customer remarks"],
                "required": False,
            },
        },
    },
    {
        "slug": "pricing_support",
        "display_name": "Pricing & support (MDF)",
        "description": "List/net pricing and MDF / support rows (pipeline scaffold; admin).",
        "enabled": True,
        "hidden": True,
        "admin_only": True,
        "requires_provider": True,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {"sku": {"aliases": ["item"], "required": True}},
    },
    {
        "slug": "lineup_plan",
        "display_name": "Line-up plan",
        "description": "Assortment / line-up planning rows (preview scaffold; use dedicated bulk flows for full upsert).",
        "enabled": True,
        "hidden": False,
        "admin_only": True,
        "requires_provider": True,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {"sku": {"aliases": ["item"], "required": True}},
    },
    {
        "slug": "promotion_plan",
        "display_name": "Promotion plan",
        "description": "Promo plan rows by SKU (pipeline scaffold).",
        "enabled": True,
        "hidden": True,
        "admin_only": False,
        "requires_provider": True,
        "pipeline_handler": "stub_noop",
        "destructive_apply_requires_confirm": False,
        "accepted_file_types": [".csv", ".xlsx"],
        "expected_columns": {"sku": {"aliases": ["item"], "required": True}},
    },
]

DEFAULT_SOURCES: list[tuple[str, str, str, str]] = [
    ("product_catalog_default", "Default product catalog feed", "product_master", "catalog"),
    ("distributor_master_default", "Default distributor master feed", "distributor_master", "master_extract"),
    ("customer_master_default", "Default customer master feed", "customer_master", "master_extract"),
    (
        "customer_channel_mapping_default",
        "Default customer/channel mapping feed",
        "customer_channel_mapping",
        "mapping_extract",
    ),
    ("customer_inv_default", "Default customer inventory feed", "customer_inventory_sales", "pos_extract"),
    ("inbound_default", "Default inbound feed", "inbound_shipments", "carrier_extract"),
    ("pricing_support_default", "Default pricing / MDF feed", "pricing_support", "pricing_extract"),
    ("lineup_plan_default", "Default line-up feed", "lineup_plan", "planning_extract"),
    (
        "historical_lineup_default",
        "Default historical lineup feed",
        "historical_lineup",
        "planning_extract",
    ),
    ("promotion_plan_default", "Default promotion plan feed", "promotion_plan", "promo_extract"),
    ("current_lineup_system", "Current working lineup (Commercial Planner upload)", "current_lineup", "planning_extract"),
]


def product_master_sample_csv() -> str:
    return (
        "sku,name,category,channel_code\n"
        "SKU-NEW-99,Example product,Audio,RET\n"
    )
